- fusesoc/config.py
- fusesoc/main.py
- fusesoc/provider/opencores.py
- fusesoc/utils.py
The Python interpreter has a few versions on Windows:
* The `mvsc` one provided by the official installer and conda
* The `gnu` ABI version provided by `msys2`
* `cygwin`, a POSIX wrapper
* A `midipix` version in the future, which is a superior POSIX wrapper.
Depending on what version/package you use, you can end up in an environment (and _not_ just due to the `PATH` variable) where Python invokes a tool that doesn't understand Windows paths. This patch adds an option to force using POSIX style PATHs if necessary using the `--cygpath` flag. The `--cygpath` flag is optional, and `Provider`s must manually provide support for the flag.
There are many cases where the `--cygpath` flag isn't required, and might not even be useful. For instance, a user who installed the `msvc` build of Python …
> Add Cygpath handling for misbehaving subprocesses

- fusesoc/section.py
Currently, I get output like this:
WARNING: Unknown section 'dpi' in 'xxx.core'
WARNING: Warning: Unknown item "top_module" in section "xsim" in yyy.core
This commit removes the second "Warning".
> Don't output "Warning" twice

- fusesoc/main.py
Use the 'fusesoc' subdirectory for the user output and also for the
directory exists check.
As the creation of the path for the library is done at a different point, this should not change the behavior for the location of the default library folder, but gives the correct default location for the user.
> Init default library location

- fusesoc/main.py
These commands were intended to be used with CAPI1 format.
> Add warnings for deprecated sim and build commands.

- fusesoc/capi2/generator.py
It seems useful to allow a generator to be run as a Python module directly from a script rather than having to be run as a separate process. For example, a script could drive fusesoc/edalize and try a core with several different package settings or clock constraints.
I think a script would rather supply the configuration data directly in a dictionary rather than going through YAML, so this change allows a script to supply the data to the generator's constructor. For backward compatibility the default case loads YAML from a file on the command line.
The generator inheriting from this base class would also need to support this usage. I'll follow up with a change to the template generator that seems to work.
> Allow generator data to be supplied to the constructor

- fusesoc/utils.py
Log verbosity preferences (e.g. passed through --verbose) are applied
only to fusesoc, not to edalize currently.
That's slightly unexpected since edalize is "invisible" to the end user
and integrated into the flow. This simple change makes the logging
settings apply to edalize as well.
> Pass on verbosity to edalize

- fusesoc/capi2/generator.py
Allow `logical_name` to be specified when adding files to a generator core file.
> generators-library

- .travis.yml
- appveyor.yml
"fusesoc update" was renamed to "fusesoc library update". Use the new
command name in CI.
> CI: Use newer library command

- .travis.yml
- appveyor.yml
- setup.py
The fusesoc unit tests run with pytest in Travis, but not in Appveyor
(Windows). Enable them there as well.
> CI: Show how to run pytest in appveyor

- fusesoc/provider/provider.py
Git 2.3.3 introduced a check to prevent git apply from modifying files
outside the current working directory. FuseSoC's usage of --directory
requires disabling this check with --unsafe-paths in newer versions of
git.
Older versions of git, including git 1.8.3 shipped with RHEL 7, don't
perform the check or support the --unsafe-paths option. Therefore using
--directory in this manner would require a git version check and setting
the git apply options based on the result.
The simpler option is just running git apply from the directory being
patched, especially since this is already supported by the Launcher
class.
> Run git apply from the directory being patched

- .travis.yml
- appveyor.yml
- doc/source/user/installation.rst
- setup.py
Python 2.7 reached EOL in the beginning of this year after being
supported for roughly 10 years. It's now time also for fusesoc to
benefit from the language and ecosystem improvements that happened since
then, and drop backwards-compat with Python 2.7. The last version to
support Python 2.7 is fusesoc 1.10, which can still be installed through
pip.
Fixes #337
> Remove support for Python 2.7

- fusesoc/config.py
Avoid a race condition between checking for the cache root and actually
creating it.
> Fix potential race condition to create cache root

- fusesoc/capi1/core.py
Using 'is' in this context is wrong (Python reserves the right to have
more than one object for a given string) and starts causing warnings
with Python 3.8.
> Use '==' instead of 'is' for literal comparisons

- .travis.yml
- appveyor.yml
Ensure that we use a recent enough version of pip and setuptools in CI to parse all pip metadata.
> Fix Appveyor CI

- fusesoc/capi2/core.py
- fusesoc/capi2/generator.py
- fusesoc/coremanager.py
- fusesoc/edalizer.py
- fusesoc/main.py
- fusesoc/utils.py
- fusesoc/vlnv.py
In preparation for some generator work, here are two more speed improvements for fusesoc.
* Use a faster YAML parser if possible. This should be quite visible in projects with a significant amount of CAPI2 core files, and a large EDAM file.
* Cache the solved dependency tree. This won't be visible at this point, since the solving only takes place once. But as part of my work on generators, the solving will need to happen more than once, and caching helps significantly in this case.
Again, see the individual commit messages for details.
> More speed improvements

- fusesoc/capi1/core.py
- fusesoc/capi2/core.py
- fusesoc/coremanager.py
- fusesoc/edalizer.py
- fusesoc/utils.py
- tests/capi2_cores/deptree/child1.core
- tests/capi2_cores/deptree/child2.core
- tests/capi2_cores/deptree/child3.core
- tests/capi2_cores/deptree/root.core
- tests/test_coremanager.py
* Add a simple test for the dependency resolution in CoreManager
* Make `CoreManager.load_cores()` private.
* Document the API of CoreManager better.
See the individual commit messages for more details.
> Cleanups to CoreManager

- tests/capi2_cores/misc/generators.core
Otherwise running the testsuite has a dependency on (at least) the
yaml library for Python 2.
> Use Python 3 in generators.core example

- fusesoc/main.py
In 57e50f282100489d8635068e13467fbe324306d0 the YAML reading
functionality got factored out into fusesoc.utils, but the import wasn't
done properly. Fix that.
Reported by Satnam Singh.
Fixes lowrisc/opentitan#1874
> Fix reading of EDAM file without configure

- fusesoc/librarymanager.py
This should have no effect when running the fusesoc program, but the
class variable can cause problems with test code (which doesn't
restart Python between different tests) because different the state
hangs around.
> Don't use a class variable for _libraries in LibraryManager

- fusesoc/utils.py
Whilst changing a core file I use from CAPI1 to CAPI2 I discovered some odd datatype behaviour that causes python to throw an exception in the utils.py file. 
Previously I used a CAPI1 core file with the name 'somecore-2019.11.core' representing version 2019.11 of 'somecore', using the year.month versioning scheme. With a new release, I thought I'd upgrade the core file to a CAPI2 one with a git provider section like:
```
provider:
name: git
repo: some_legal_git_url
version: 2020.01
```
Unfortunately, this fails to check out because the version field is interpreted by the YAML safe_load function in capi2/core.py as a float. This gets passed through to the utils file whose
calls to join and check_call error as they expect strings and not floats.
This change makes sure that string …
> Stringify args for calls to debug prints and subprocess

- fusesoc/coremanager.py
We've talked about this before. For some of our old repos with big histories, fusesoc ends up spending a lot of time (~minutes) looking through .git subdirectories. I've had a tab open meaning to fix this but was finally pushed to do it.
Note that I made the exclude directories a set so we can add other things we should exclude.
> Ignore .git subdirectories

- fusesoc/capi2/core.py
In some cases os.path.exists may return False,
even if the path exists. In such scenarios running
FuseSoc results with FileExistsError. Letting
os.makedirs handle existing directories avoid such
buggy corner cases.
> Let os.makedirs handle existing directories.

- fusesoc/main.py
We were calling `get_edatool(tool)` twice: once for parsing backend
arguments and then again to do the actual work. The first call wasn't
surrounded by a try/catch for `ImportError`. This meant that if you
asked for a bogus tool (with a typo in your corefile), a
`ModuleNotFoundError` would make it to the console.
This patch surrounds the call to `get_edatool` with the try/catch block.
It also uses the `backend_class` that we found, rather than calling
`get_edatool` again.
> Catch error when backend tool is unknown

- fusesoc/capi2/core.py
- fusesoc/capi2/exprs.py
- tests/test_exprs.py
This defines an `Exprs` class (in a new `exprs.py`) that holds a simple
parsed AST for a string. The String class in core.py now wraps one of
those, memoizing the "parse a string to an AST" part.
This speeds up parsing large core files significantly. For example,
without this patch the OpenTitan project takes roughly 4.5 seconds to run
```
fusesoc --cores-root=. run --target=sim --setup \
lowrisc:systems:top_earlgrey_verilator
```
With this patch, it takes about 2.2 seconds.
> Separate parsing and expanding Strings in core.py

- fusesoc/edalizer.py
Whilst experimenting with relative cache_root's in our CI setup, I've stumbled across an incompatibility between generators and relative cache_root settings. 
If you provide a fusesoc.conf file that contains the following, then generators are unable to read their generator_input_file yaml file, as the filepath is described as relative to cache_root, whilst the working directory is inside the generator folder:
```
[main]
cache_root = ./relative-cache
```
By converting the generator_input_file path using the abspath function, the generators can find their input file even if the user has configured their fusesoc.conf file to specify a relative path to cache_root. If the cache_root is already fully specified, then this change has no effect.
> Pass generator_input_file using absolute path to support relative cache_root settings

- fusesoc/main.py
- fusesoc/utils.py
The same functionality can be obtained through "fusesoc run". We did 
deprecate the other special cases (fusesoc build and fusesoc sim) quite a
while ago, but apparently forgot to do the same for "fusesoc pgm". Do that
now, and remove it in the next release.
> Deprecate "fusesoc pgm"

- setup.py
This bit of meta-information was missed when doing the license
migration, adjust that to show the right information at PyPi.
> FuseSoC is now BSD-licensed, update setup.py

- tests/capi2_cores/deptree/child1.core
- tests/capi2_cores/deptree/child2.core
- tests/capi2_cores/deptree/child3.core
- tests/capi2_cores/deptree/child4.core
- tests/capi2_cores/deptree/generated_child_a.core
- tests/capi2_cores/deptree/generated_child_a.py
- tests/capi2_cores/deptree/root.core
- tests/test_coremanager.py
Recent refactoring of the Edalizer class introduced a bug where the files in the generated .eda are not in a dependency-consistent order.
This fixes this bug, by keeping track of how the generated cores are positioned in the ordered list of cores.
> Fix regression in the file order of designs with generators.

- .github/workflows/ci.yml
- .github/workflows/lint.yml
- fusesoc/edalizer.py
- tox.ini
Right now, we run pull request CI jobs in the context of the olofk/fusesoc
repository. We did this to be able to create Check runs, which show the
pytest results in the GitHub UI. There are multiple problems with that:
First, the runs actually didn't contain any data. That's probably fixable
if we found the right configuration regarding test result files and
artifacts.
Second, and more importantly, it seems that the "old" test code was run, 
i.e. pytest didn't pick up test changes done in the PR. That's hard to 
believe, but also not very useful, as PRs often modify code and tests at 
the same time. There might be some misconfiguration going on somewhere, but
I didn't debug it fully.
Finally, the test result reporting action we used is actually rather slow
(significantly slower than the …
> CI: Run test in forked repo context

- doc/source/ref/capi1.rst
- doc/source/ref/migrations.rst
The content is still outdated, but at least it now renders.
> Fix markup in CAPI1 documentation

- tests/capi2_cores/deptree/generated_child_a.core
- tests/capi2_cores/deptree/generated_child_a.py
- tests/test_coremanager.py
The position attriute is meant to insert files generated by the core at
a specific location: after the chosen core, at the beginning of the file
list, or at the end. This behavior was not tested so far. Add a test for
it.
> Test the position attribute for generate blocks

- fusesoc/capi2/core.py
- tests/capi2_cores/files_out_of_hierarchy/subdir/files_out_of_hierarchy.core
- tests/test_capi2.py
The core file is expected to be at the root directory of an IP core, as
understood by FuseSoC; including files from files outside (above) this
directory was never really supported by FuseSoC, but we didn't error out
on it either. Add a deprecation warning with the intent to remove this
functionality in the next major release.
First part of #264
> Deprecate using files out of the core boundary

- tests/test_vlnv.py
This test is part of the file twice, likely a copy-paste error.
> Remove duplicated test

- doc/source/conf.py
Add information about the version the documentation is built for to the
rendered documentation. This information is identical to the data shown
with `fusesoc --version` and ultimately derived from the tags in the Git
source tree by setuptools_scm.
> Add version information to documentation

- .editorconfig
To quote editorconfig.org:
"EditorConfig helps maintain consistent coding styles for multiple
developers working on the same project across various editors and IDEs.
The EditorConfig project consists of a file format for defining coding
styles and a collection of text editor plugins that enable editors to
read the file format and adhere to defined styles. EditorConfig files
are easily readable and they work nicely with version control systems."
This commit adds a very basic editorconfig file to catch the most common
cases.
> Add a editorconfig file

- fusesoc/core.py
- tests/test_capi1.py
The CAPI1 core description format has been deprecated for a while in our
documentation, but users of FuseSoC didn't, up to now, get a deprecation
warning when running `fusesoc`. Add such a warning to encourage users to
switch to CAPI2.
Commit deprecating CAPI1 in our docs: c03b095cf7d40e00d476ba5507c8e60a22286459 (Feb 2019)
Related to #361
> Issue deprecation warning for CAPI1

- .git-blame-ignore-revs
When using `git blame`, ignore commits which are only reformatting the
source code. This makes it easier to see who actually changed the line
functionally, instead of always referring to commits which reformatted
the whole source code.
> Ignore reformatting commit in git blame

- doc/requirements.txt
- doc/source/conf.py
- doc/source/user/installation.rst
When building the documentation we now execute `fusesoc --version` to
ensure that the documentation gives exactly the same output as the user
is expected to get, as long as they are reading the documentation
matching their installed version.
As a slight downside, we loose syntax highlighting for that block,
making it inconsistent with the other command snippets on the page. It's
fixable, but didn't seem worth it for now.
> Show actual version output for documented version

- fusesoc/capi2/core.py
The current code expands environment variables in
`targets.*.generate` blocks. This behavior is not documented and was
likely introduced in error in commit 4d02c089. Since we haven't released
this feature yet, let's remove it.
Example: before this patch, the following was possible, assuming
`TESTGEN_ENV_VAR` was set to `testgen`.
```
name : ::expandvars:0
generators:
generator1:
interpreter: python3
command: testgen.py
targets:
default:
generate:
- $TESTGEN_ENV_VAR
toplevel: na
generate:
testgen:
generator: generator1
```
> Remove variable expansion from generate names

- doc/source/conf.py
We were using the old html_context which has been deprecated
for a while. This PR switches to html_css_files instead.
See sphinx-doc/sphinx#8885 for more information.
> Fix deprecated sphinx html_context usage in conf.py

- fusesoc/main.py
Currently, FuseSoC is only usable with its entrypoint. This adds the capability to use it as module by calling fusesoc.main.fusesoc(args). The parser can be instantiated separately to build the proper args object.
> Better usability as module

- .github/workflows/ci.yml
- doc/source/user/installation.rst
- setup.py
- tox.ini
Python 3.5 is EOL upstream; remove support for it from FuseSoC to enable
us to use newer features.
Fixes #454
> Require Python 3.6

- doc/source/user/package_manager/index.rst
- tox.ini
`fusesoc init` is deprecated, do not use it in the docs or in our
testing.
> Avoid the use of "fusesoc init"

- fusesoc/main.py
Disable tool output during the build phase by default. If build returns an error, the buffered stdout and stderr will be printed on the terminal. Running `fusesoc --verbose` reenables tool output
> Disable Edalize verbose mode by default

- doc/source/dev/devsetup.rst
- fusesoc/capi2/core.py
- tox.ini
sphinx-autobuild builds the documentation, serves it on a localhost web
server, automatically rebuilds it when changes are detected, and also
refreshes the web page automatically. With this setup documentation
writers can have the documentation open in their browser, change
documentation source code, and see the updated documentation as soon as
they save the source file, without any other action needed. Beautiful!
Add the tox setup for this, and document it as the preferred way of
working on documentation. The more manual way remains in place for now.
Additionally, this PR contains small two cleanup commits that I came across.
> Setup and document the use of sphinx-autobuild

- doc/source/ref/glossary.rst
- doc/source/user/build_system/core_files.rst
- doc/source/user/build_system/flags.rst
- fusesoc/capi2/core.py
This PR contains two commits which depend on each other, but are different topics:
- The first commit recommends to always quote strings used as value in CAPI2 files. This gives our users a single, always-right and easy to remember rule on what to do with strings. All other rules are more complex ("quote some strings, but not others") and easy to get wrong (as multiple support requests I've gotten over the recent months have shown).
- The second commit documents flags and their uses in FuseSoC, filling a gap in the documentation.
> Document use flags, and recommend quoted YAML strings

- dev-requirements.txt
The recommended way of building the documentation locally is through
tox. Avoid installing Sphinx for "manual" development environments, tox
already takes care of that.
Add tox as development dependency (it was missing before), and remove
the manual installation of Sphinx.
For now we keep pytest as separate dependency, even though that's not
needed when running tests through tox.
> Remove Sphinx from dev-requirements.txt, add tox

- fusesoc/capi2/core.py
This commit add basic Integer class to support Integer type parameters for back ends defined in edalize. For example: jobs parameter of Vivado. Please see Issue #515 https://github.com/olofk/fusesoc/issues/515
Fixes #515
> Add Integer class for edalize

- fusesoc/edalizer.py
- copyto now supports copying directories to the workspace. This is useful
for copying directories such as Xilinx board files for Vivado.
> feat_board_file_support: adding support for copying directories

- .github/workflows/ci.yml
Python 3.11 is in alpha now, but having it in CI helps us be prepared.
CI will always pick up the latest 3.11 version as it moves from alpha to
beta to release ultimately.
> CI: Add Python 3.11 (alpha for now)

- fusesoc/main.py
These two commands have been deprecated for a while, remove them while
still showing a message to our users informing them what to do instead.
> Remove fusesoc pgm and fusesoc init

- fusesoc/capi2/core.py
- there are two locations in the codebase where file copying takes place depending
on whether you run fusesoc with the --no-export switch.
> feat_board_file_support: fix for missing copytree

- tox.ini
Avoid removing the full (tox-created) HOME directory, as it may contain
Python venv components that we are unable to delete at times.
Fixes #546
> Tox: More selectively remove directories

- tests/test_edalizer.py
This didn't matter until 0469da4 because all the 'core_root' paths
were the same. But generated cores now appear in different directories
from one another so we have to get it right.
Note that this isn't actually required for upstream at the moment: it's probably nice to be more robust, but things were working anyway. But it *is* required for some local changes we've got on our OpenTitan fork where @imphil's patch reorders generated cores a bit (and the "-3" and "-2" indices were then wrong).
> Tweak test_edalizer not to depend on the order of edalizer.cores

- fusesoc/capi2/core.py
- fusesoc/coremanager.py
- tests/capi2_cores/virtual/impl1.core
- tests/capi2_cores/virtual/impl2.core
- tests/capi2_cores/virtual/user.core
- tests/test_capi2.py
- tests/test_coremanager.py
Packages can now provide more than one package: they provide itself (as
described by the package `name`), and a list of further (virtual)
packages, described by the `virtual` key in the root of the CAPI2 file.
Example:
```
CAPI=2:
name: ::impl2:0
virtual:
- ::someinterface:0
```
This core provides a core named `::impl2:0` and a core named
`someinterface:0`. Other cores can now depend either `::impl2:0` or
`::someinterface` and always get the `::impl2:0` core.
The keyword `virtual` was chosen over alternatives, such as `provide` to
be distinct from other keywords we use in CAPI2 currently, especially to
be distinct from the concept of providers.
Fixes #235
> Support virtual packages in CAPI2

- tests/test_coremanager.py
Commit 6b04028491c02308bec9423627c35b3456ea980a introduced new code
which broke a test. Fix that. (There was a mid-air collision of two
changes.)
> Fix interface incompatibility in test_virtual

- .pre-commit-config.yaml
- fusesoc/provider/provider.py
Pull request regarding issue [562](https://github.com/olofk/fusesoc/issues/562)
I did need to update the black version otherwise my pre_commit was falling all the time with a corresponding error.
> provider clean_cache rmtree working on windows with ro files in .git

- .flake8
- .pre-commit-config.yaml
- fusesoc/capi2/core.py
- fusesoc/config.py
- fusesoc/coremanager.py
- fusesoc/edalizer.py
- fusesoc/main.py
- tests/test_config.py
- tests/test_coremanager.py
- tests/test_edalizer.py
- tests/test_ignored_dirs.py
- tests/test_libraries.py
The first 3 commits in this PR are minor cleanups. The most interesting (controversial?) bit is probably the first:
- **Bump to a working version of Black**: Although we've pinned Black to version 20.8b1, this doesn't pin the "click" library on which it depends. Bump Black to a version that works with the latest click.
After that, I made a couple of tidy-up commits in `config.py`. Then this commit might need a bit of thought:
- **Interpret relative paths in config file relative to it, not CWD**: This changes behaviour, but probably to something more useful than what we had before. I'd be very surprised if we had any users relying on the fact that relative paths in a config file were interpreted relative to CWD.
Finally, we can add the `ignored_dirs` key that motivated the whole thing.
> Add support for ignored directories to config files

- doc/source/user/build_system/tool_options.rst
- fusesoc/main.py
This adds `fusesoc tool list` to the CLI. A FuseSoC `tool show <tool>` should be added as well but might benefit from some refactoring first to get nice option printing like when running `fusesoc run <core> --help`.
Also, once we pull in the flow API, corresponding `fusesoc flow show/list` will be added as well
> Add CLI for listing tool backends

- fusesoc/provider/git.py
No-single-branch flag ensures shallow-clone depth constraint does not make older tags invisible
(Issue #576)
> Make sure shallow clone pulls all tags

- fusesoc/capi2/exprs.py
- tests/test_exprs.py
Passing tool arguments such as -CFLAGS "blah blah" requires '"'.
> Allow double quotes in string expressions

- setup.py
I tested FuseSoC with all versions of pyparsing, pyyaml, fastjsonschema, jsonschema2md, and myst_parser. I found and added the minimum required versions. (fastjsonschema and jsonschema2md can be any version)
This fixes a setup issue I was having
> Fixed setup dependency versions

- fusesoc/capi2/core.py
- tests/test_capi2.py
This commit updates the output of `fusesoc core show` to add the filename of the core file itself. This change is required for tools such as the filelist Edalize backend as discussed in
https://github.com/olofk/edalize/issues/25.
The output of `fusesoc core show` now looks like:
CORE INFO
Name:        vee:el:en:vee
Description: Top bombing
Core root:   /root/path/to/core/file
Core file:   basename.core
> Add core filename to output of `fusesoc core show`.

- fusesoc/capi2/inheritance.py
- fusesoc/utils.py
- tests/capi2_cores/parser/inheritance.core
- tests/test_capi2.py
Fixes #639 and fixes #624
In summary, inheritance is no longer implemented by PyYAML's merge key implementation. Instead, it is overridden by a custom FuseSoC implementation
* Added [fusesoc/capi2/inheritance.py](https://github.com/sifferman/fusesoc/blob/9af5a0ef42d96a8761090cc0b5abbe0c379340da/fusesoc/capi2/inheritance.py) to centralize logic related to inheritance
* `utils.yaml_fread()` now calls `utils.yaml_read()` to improve code reusability
* <ins>**Possibly**</ins> fixed small bug in `utils.yaml_read()` by changing `data.read()` to `data`. (There is no test in the CI that checks for this case, so I am uncertain whether this change is good)
* `utils.yaml_read()` now replaces all merge key operators (`<<`) with an intermediate value of `Inheritance.MERGE_OPERATOR`, then turns the YAML …
> Improved inheritance

- fusesoc/config.py
- fusesoc/main.py
- tox.ini
To allow for the CI to run the windows tests again, I've done the bare minimum to get the tox test runner to run again under Windows. There are failing tests but, the purpose of this pull request is just to make it run again.
* Resolve XDG paths in a OS independent way (using `pathlib.Path` to do all `\` and `/` convertions)
* Create directories for config file if they doesn't exist. 
* Workaround for removal of `tmp` XDG files on windows. *`shutil.rmtree` sometimes fails one windows, seems to be UAC related.*
Needs to run on the CI for Linux verdict just tested for python versions 3{6-11} on windows 11 😄
> Enable windows tests again, the first steps (#528)

- fusesoc/main.py
- tests/test_coremanager.py
The "tool list" command line argument was returning nothing when invoked.
After quick inspection, I noticed an import statement was missing and was able to make the very minor fix.
> "tool list' CLI argument now functional

- pyproject.toml
Adding a pyproject.toml with a build backend is the essential first step in modernizing a Python project, as it sets the foundation for utilizing PEP 517 and PEP 518 standards, enabling improved packaging, dependency management, and compatibility with modern build tools, as detailed in the packaging guide: https://packaging.python.org/en/latest/guides/modernize-setup-py-project/#where-to-start.
This update facilitates building and installation using the following recommended commands:
Deprecated | Recommendation
-- | --
python setup.py install | python -m pip install .
python setup.py develop | python -m pip install --editable .
python setup.py sdist | python -m build
python setup.py bdist_wheel | python -m build
> Modernize python packaging with pyproject.toml and build-backend

- fusesoc/coremanager.py
- tests/capi2_cores/virtual/top_impl1.core
- tests/capi2_cores/virtual/top_impl2.core
- tests/test_coremanager.py
Add "conflicts" constraints for each core implementing virtual VLNVs, so no two cores implementing the same virtual VLNV may be selected simultaneously.
This change should prevent more than a single implementing core from being selected as the implementation for a virtual VLNV, and when there is an explicit dependency in the tree, that one should be selected.
> coremanager: Pick preferred cores for virtual VLNVs

- fusesoc/edalizer.py
logging.warn is an alias to logging.warning since Python 3.3 and will be removed in Python 3.13.
> Replace logging.warn usage with logging.warning

- pyproject.toml
This version contains fixes for Python 3.11 and 3.12.
In particular, there were some backslashes in doc comments that were causing syntax warnings in 3.12.7 which are now fixed:
https://github.com/enthought/sat-solver/commit/40f156198042c898e423f4f41da520f3d608d172#diff-05260edff2f9de014b7a81dede2c6fcfc28947d2b9409ae2d8dcaaef090e001fR77
> Update simplesat to 0.9.1

- fusesoc/edalizer.py
Fixes #673
The issue was caused by 90500180872ed26c3bee2c41c50be5ff0b49c2b4
I also checked, that this fix does not break  #616 again
> Fixed Generator Cache with --no-export

- fusesoc/fusesoc.py
- fusesoc/librarymanager.py
- tests/test_libraries.py
As mentioned in #603, it is tempting to check in the `fusesoc.conf`-file into a version control system. This way all the necessary libraries are written down explicitly and changes are tracked as well. Note, that this is not the intended workflow, but it _almost_ works with fusesoc version 2.4.2, except for one usecase:
in a clean checkout of a repository, there is the `fusesoc.conf`, but crucially not the `fusesoc_library`. In this case, almost all `fusesoc`-commands will fail with an error like this:
```shell
$ ls fusesoc_libraries fusesoc.conf
ls: cannot access 'fusesoc_libraries': No such file or directory
fusesoc.conf
$ cat fusesoc.conf
[library.vlog_tb_utils]
location = fusesoc_libraries/vlog_tb_utils
sync-uri = https://github.com/fusesoc/vlog_tb_utils
sync-type = git
auto-sync = …
```
> Perform an initial checkout if library is missing

- fusesoc/provider/github.py
- fusesoc/provider/url.py
This commit addresses some warnings issued by Python 3.12+ with regards to the behavior of `tarfile.extractall()`. Currently that method gets called in two places: the URL and GitHub provider. Both essentially trust the archive to not be malicious at the moment: tarfiles can be crafted to overwrite other parts of the system and have strange links or even device files...
[PEP 706] tries to fix this potential security vulnerability in a large amount of code written today by restricting changing the behavior of the aforementioned method in Python 3.14. At the moment, a warning is issued to apply a suitable filter parameter. This commit uses such a filter, if the python version running the code supports it.
The implementation is based on conda/conda-package-streaming#96, which is a pull …
> Fix `tarfile`-warnings due to PEP 706

- tests/test_libraries.py
The new test `test_library_update_with_initialize` introduced in #720 did use the `fusesoc_libraries`-directory in the repository root and, in contrast to other tests in that module, did not delete it afterwards. This causes a leftover library in the repository root after running the testsuite. This is unpleasant and a bug in the test.
This commit fixes it by cloning into the temporary directory, which was already created for just this use-case.
> Don't leave back stray library after tests

- fusesoc/config.py
- tests/test_config.py
Currently FuseSoC has two problems related to relative path resolution, 
The more severe one occurs when the fusesoc.conf file is in the current directory, in that case the code 
[files_read = self._cp.read(config_files)](https://github.com/olofk/fusesoc/blob/b604f53daf3c28aedd196c5cc1335f3161280201/fusesoc/config.py#L40)
returns only the file name, then in the function [_resolve_path_from_cfg](https://github.com/olofk/fusesoc/blob/b604f53daf3c28aedd196c5cc1335f3161280201/fusesoc/config.py#L95-L107) when `os.path.dirname` is called, an empty string is returned and when joined to form the final path we get a broken result
A second issue that I found is when referencing to a relative path starting with a dot, for example `./build_root` that dot stays in the path producing a result like …
> Fix erroneous relative path resolution

- fusesoc/config.py
- fusesoc/coremanager.py
- tests/test_config.py
This PR fixes the macOS tests, which were broken by pull request #726 . The issue occurs because on macOS, **/var** and **/tmp** are symbolic links to **/private/var** and **/private/tmp**. When calling `abspath` on a relative path or filename, we get the canonical (real) path. However, the `TemporaryDirectory()` function used in the tests returns a symbolic link that is already an absolute path (starting with **/var**), so calling `abspath` on it does nothing.
I also replaced the `abspath` call when processing the ignored directories with `realpath` to avoid a mismatch between a symlink and the canonical path of the same directory.
Everything seems to be working now, but I'm still a bit worried that there might be another comparison between symlink paths and real paths elsewhere in the …
> Fix canonical path vs symlink comparison

- fusesoc/provider/git.py
- tests/test_usecases.py
See #721 for context. This PR uses `git fetch` instead of `git pull` when on a git tag. This won't cause any errors on git tags and thus the library update won't fail. It even supports switching to a new tag, when the `sync-version`-field in the `fusesoc.conf`-file is altered.
Best reviewed commit-by-commit:
* The first commit is just some housekeeping.
* The second commit introduces a new test module, which comes in very handy for testing sequences of shell commands. The module contains a fixture, which will run the testcase in a temporary directory. The `_fusesoc()`-function can be used to run shell commands. I'm a little bit proud of how the test module turned out: there is almost no boilerplate in actual test functions.
* The last commit contains the actual change.
Fixes #721.
> Don't error on `fusesoc library update` when `sync-version` is used for a git-provided library

- fusesoc/main.py
Adds a clean flag that explicitly cleans (deletes) the build directory when using the flow API.
> Added --clean flag to fusesoc run command

- fusesoc/main.py
- pyproject.toml
The current bash_completion script is very basic and the completion breaks after entering the first letter of a core name.
Since fusesoc uses the argparse package for argument parsing, we can use the argcomplete package for bash_completion.
Most of the completion is done automatically by argcomplete using the argparse parser.  So there is no need to replicate argument/subparser names in a separate bash_completion file.
I also implemented completion for cores, generators and tools for the specific arguments.
Completion for bash/zsh can be enabled either globally or on a per-command basis.
Global completion can be enabled with the _activate-global-python-argcomplete_  command. Additionally, the fusesoc binary needs the string PYTHON_ARGCOMPLETE_OK in the first 1024 bytes. I would have added …
> Add better bash_completion with the argcomplete package

- doc/source/user/build_system/index.rst
- doc/source/user/build_system/mappings.rst
- doc/source/user/build_system/virtual_cores.rst
- fusesoc/capi2/core.py
- fusesoc/capi2/json_schema.py
- fusesoc/coremanager.py
- fusesoc/main.py
- fusesoc/vlnv.py
- tests/capi2_cores/mapping/a.core
- tests/capi2_cores/mapping/b.core
- tests/capi2_cores/mapping/c.core
- tests/capi2_cores/mapping/d.core
- tests/capi2_cores/mapping/e.core
- tests/capi2_cores/mapping/f.core
- tests/capi2_cores/mapping/map_rec.core
- tests/capi2_cores/mapping/map_vers.core
- tests/capi2_cores/mapping/top.core
- tests/test_coremanager.py
Introduce the mappings feature discussed in https://github.com/olofk/fusesoc/pull/727. *See https://github.com/olofk/fusesoc/pull/727#issuecomment-2647695340 for context.*
Description of the feature from the documentation:
> Mappings allow a user of a core to substitute dependencies of the core with other cores without having to edit any of the core or it's dependencies files. An example use case is making use of an existing core but substituting one of it's dependencies with a version that some desired changes (e.g. bug fixes).
I've restricted the flexibility of mappings in the interest of keeping this patch set smaller:
- They cannot be recursive.
- They cannot include versions.
- Cores conflicting with substitutes aren't removed from the dependency tree.
- For OpenTitan's use case, a …
> Introduce the mappings feature

- fusesoc/capi2/core.py
Since items the src_files list start with './' for files from a generated core (or at least for the core I'm experimenting with), the files should be normalized before comparison. Otherwise, all of the generated files will be removed, and no export takes place.
> Export generator files successfully

- doc/requirements.txt
- pyproject.toml
`jsonschema2md` is not actually needed by FuseSoC it's self. It's only needed for documentation, so should live in `doc/requirements.txt`.
I found this when updating the nixpkgs' version of FuseSoC (https://github.com/NixOS/nixpkgs/pull/419605). `jsonschema2md` is nasty to package due to a seemingly cyclical dependency in the build of one of it's build dependencies: https://github.com/sbrunner/poetry-plugin-tweak-dependencies-version/blob/e40b1a1093109639d99ff0d4f33f430252dae9e4/pyproject.toml#L77
> Moved jsonschema2md to doc requirements

- fusesoc/capi2/json_schema.py
Adds support for specifying license information in the CAPI2
schema. The license can be provided as an SPDX identifier string
or as a custom license object with name and text attributes.
This allows for better documentation and identification of the
licenses used in FuseSoC cores.
> Adds license field to CAPI2 schema
